---
- name: Deploy Fitness Booking Application
  hosts: webservers
  become: yes
  vars:
    app_name: fitness-booking
    docker_compose_dir: /opt/{{ app_name }}
    docker_compose_file: docker-compose.prod.yml
    docker_hub_username: telesphoreuwabera
    docker_hub_image: fitness-booking

  tasks:
    - name: Install required packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - docker.io
          - docker-compose
          - python3-pip
          - git

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create application directory
      file:
        path: "{{ docker_compose_dir }}"
        state: directory
        mode: '0755'

    - name: Copy docker-compose file
      copy:
        src: "{{ docker_compose_file }}"
        dest: "{{ docker_compose_dir }}/{{ docker_compose_file }}"
        mode: '0644'

    - name: Copy .env file
      copy:
        src: .env.prod
        dest: "{{ docker_compose_dir }}/.env"
        mode: '0600'

    - name: Login to Docker Hub
      docker_login:
        username: "{{ docker_hub_username }}"
        password: "{{ docker_hub_token }}"
      no_log: true

    - name: Pull latest Docker images
      docker_compose:
        project_src: "{{ docker_compose_dir }}"
        files:
          - "{{ docker_compose_file }}"
        pull: yes

    - name: Stop existing containers
      docker_compose:
        project_src: "{{ docker_compose_dir }}"
        files:
          - "{{ docker_compose_file }}"
        state: absent

    - name: Start containers
      docker_compose:
        project_src: "{{ docker_compose_dir }}"
        files:
          - "{{ docker_compose_file }}"
        state: present
        restart: yes
        recreate: yes
        remove_orphans: yes 